let productos = new Array();

// Aca deberia cargar todos mis productos! dejando a los destacados diferenciados.

productos = [
    {id: 1, img: "./img/productos/almendra-pd.1.jpg", descripcion: "Almendras 1kg", precio: 800, destacado: 1, seccion: "cereal"},
    {id: 2, img: "./img/productos/noquis-papa.jpg", descripcion: "Noquis de papa", precio: 220, destacado: 1, seccion: "lacteos"},
    {id: 3, img: "./img/productos/barracereal-pd.3.jpg", descripcion: "Barra de Cereal", precio: 130, destacado: 0, seccion: "cereal"},  
    {id: 4, img: "./img/productos/Miel-pd.4.jpg" , descripcion: "Miel 500gr", precio: 280, destacado: 1, seccion: "dulces"},
    {id: 5, img: "./img/productos/Arroz.jpeg" , descripcion: "Arroz Yamani", precio: 300, destacado: 0, seccion: "cereal"},
    {id: 6, img: "./img/productos/Granola.jpeg" , descripcion: "Granola 500gr", precio: 250, destacado: 0, seccion: "cereal"},
    {id: 7, img: "./img/productos/trigo-inflado.jpg" , descripcion: "Trigo inflado 1kg", precio: 380, destacado: 0, seccion: "cereal"},
    {id: 8, img: "./img/productos/Sesamo.png" , descripcion: "Semillas de sesamo", precio: 270, destacado: 0, seccion: "cereal"},
    {id: 9, img: "./img/productos/Cereal-Almohaditas.jpeg" , descripcion: "Almohadita 500gr", precio: 350, destacado: 0, seccion: "cereal"},
    {id: 10, img: "./img/productos/MixFrutosSecos.jpeg" , descripcion: "Frutos Secos 1kg", precio: 760, destacado: 0, seccion: "cereal"},
    {id: 11, img: "./img/productos/DulceLeche.jpeg" , descripcion: "Dulce de Leche", precio: 240, destacado: 0, seccion: "dulces"},
    {id: 12, img: "./img/productos/Mermelada.jpeg" , descripcion: "Mermelada organica", precio: 320, destacado: 0, seccion: "dulces"},
    {id: 13, img: "./img/productos/pastamani.jpeg" , descripcion: "Pasta de Mani natural", precio: 360, destacado: 0, seccion: "dulces"},
    {id: 14, img: "./img/productos/azucar-mascabo.jpeg" , descripcion: "Azucar mascabo", precio: 300, destacado: 1, seccion: "dulces"},
    {id: 15, img: "./img/productos/azucar-rubia.jpeg" , descripcion: "Azucar rubia", precio: 450, destacado: 0, seccion: "dulces"},
    {id: 16, img: "./img/productos/hileret-sobres.jpeg" , descripcion: "Hileret sobres", precio: 260, destacado: 0, seccion: "dulces"},
    {id: 17, img: "./img/productos/stevia-liquido.jpeg" , descripcion: "Hileret liquido", precio: 320, destacado: 0, seccion: "dulces"},
    {id: 18, img: "./img/productos/Te-Verde.jpeg" , descripcion: "Te Verde suelto 100gr", precio: 190, destacado: 0, seccion: "infusiones"},
    {id: 19, img: "./img/productos/Te-Negro.png" , descripcion: "Te Negro 300gr", precio: 300, destacado: 0, seccion: "infusiones"},
    {id: 20, img: "./img/productos/Yerba antiacida.jpeg" , descripcion: "Yerba antiacida 1kg", precio: 840, destacado: 0, seccion: "infusiones"},
    {id: 21, img: "./img/productos/Yerba organica.jpeg" , descripcion: "Yerba organica 500gr", precio: 530, destacado: 0, seccion: "infusiones"},
    {id: 22, img: "./img/productos/yerba-hierbas.jpeg" , descripcion: "Yerba con Hierbas", precio: 369, destacado: 0, seccion: "infusiones"},
    {id: 23, img: "./img/productos/yerba-naranja.jpeg" , descripcion: "Yerba con Naranja", precio: 369, destacado: 0, seccion: "infusiones"},
    {id: 24, img: "./img/productos/cacao.jpeg" , descripcion: "Cacao en polvo 500gr", precio: 900, destacado: 0, seccion: "infusiones"},
    {id: 25, img: "./img/productos/boldo.jpeg" , descripcion: "Te Boldo en caja", precio: 380, destacado: 0, seccion: "infusiones"},
    {id: 26, img: "./img/productos/lechealmendras.jpeg" , descripcion: "Leche de almendras 1lt", precio: 280, destacado: 0, seccion: "lacteos"},
    {id: 27, img: "./img/productos/Queso.jpg" , descripcion: "Queso Sardo 100gr", precio: 130, destacado: 0, seccion: "lacteos"},
    {id: 28, img: "./img/productos/queso.cremoso.jpg" , descripcion: "Queso Tybo 100gr", precio: 90, destacado: 0, seccion: "lacteos"},
    {id: 29, img: "./img/productos/Yogur-bebible-light-frutilla.jpg" , descripcion: "Yogurt Bebible frutilla", precio: 300, destacado: 0, seccion: "lacteos"},
    {id: 30, img: "./img/productos/vegetalex-pd.2.jpg" , descripcion: "Vegetalex caja 4u.", precio: 240, destacado: 0, seccion: "lacteos"},
    {id: 31, img: "./img/productos/yogurt.jpeg", descripcion: "Yogurt con cereales", precio: 230, destacado: 0, seccion: "lacteos"},
    {id: 32, img: "./img/productos/queso-chedar.jpeg" , descripcion: "Queso Cheddar", precio: 460, destacado: 0, seccion: "lacteos"},
    ]